-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.galaxy
(
    galaxy_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    age_in_millions_of_years integer,
    galaxy_types_id integer,
    CONSTRAINT galaxy_pkey PRIMARY KEY (galaxy_id),
    CONSTRAINT unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.galaxy_types
(
    galaxy_types_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    is_spherical boolean,
    CONSTRAINT galaxy_types_pkey PRIMARY KEY (galaxy_types_id),
    CONSTRAINT galaxy_types_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.moon
(
    moon_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    planet_id integer,
    is_visited boolean,
    CONSTRAINT moon_pkey PRIMARY KEY (moon_id),
    CONSTRAINT moon_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.planet
(
    planet_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    age_in_millions_of_years integer,
    distance_from_earth numeric(10, 2),
    planet_types_id integer,
    star_id integer,
    CONSTRAINT planet_pkey PRIMARY KEY (planet_id),
    CONSTRAINT planet_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.planet_types
(
    planet_types_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    is_habitat boolean NOT NULL,
    CONSTRAINT planet_types_pkey PRIMARY KEY (planet_types_id),
    CONSTRAINT planet_types_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.star
(
    star_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    age_in_millions_of_years integer,
    distance_from_earth numeric(10, 2),
    galaxy_id integer,
    CONSTRAINT star_pkey PRIMARY KEY (star_id),
    CONSTRAINT star_name_key UNIQUE (name)
);

ALTER TABLE IF EXISTS public.galaxy
    ADD CONSTRAINT galaxy_galaxy_type_id_fkey FOREIGN KEY (galaxy_types_id)
    REFERENCES public.galaxy_types (galaxy_types_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.moon
    ADD CONSTRAINT moon_planet_id_fkey FOREIGN KEY (planet_id)
    REFERENCES public.planet (planet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.planet
    ADD CONSTRAINT planet_planet_types_id_fkey FOREIGN KEY (planet_types_id)
    REFERENCES public.planet_types (planet_types_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.planet
    ADD CONSTRAINT planet_star_id_fkey FOREIGN KEY (star_id)
    REFERENCES public.star (star_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.star
    ADD CONSTRAINT star_galaxy_id_fkey FOREIGN KEY (galaxy_id)
    REFERENCES public.galaxy (galaxy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;